services:
  db:
    image: pgvector/pgvector:0.8.0-pg16
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - $HOME/docker/volumes/MusicThing/postgres:/var/lib/postgresql/data
